version: '2'

volumes:
  datafiles:

services:
  mysql:
    image: mysql:8.0.0
    container_name: mysql8
    volumes:
      - datafiles:/var/lib/mysql
      - ./init/dump.sql:/docker-entrypoint-initdb.d/dump.sql
    restart: always
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_USER=testappuser
      - MYSQL_PASSWORD=testapppassword
      - MYSQL_DATABASE=testapp
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "9906:3306"

  website:
    container_name: php73
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
      - "8083:443"
    depends_on:
      - mysql